### Import Libraries

In [ ]:
import sklearn
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

### Load Data

In [ ]:
# read csv file
df = pd.read_csv('spotify_churn_dataset.csv')

x = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values


### One-Hot Encoding Categorical Data

In [ ]:
enc = OneHotEncoder()
ct = ColumnTransformer(transformers=[('encoder', enc, [0, 2, 3])])
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1. 0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0. 1.]
 [0. 1. 0. 1. 1. 0.]
 ...
 [1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0. 1.]]


### Build KNN Model